import {
  ArrowRight,
  BookOpen,
  Brain,
  Briefcase,
  CalendarDays,
  Check,
  ClipboardCheck,
  Clock,
  Compass,
  Download,
  FileText,
  GraduationCap,
  HeartPulse,
  Home,
  LayoutTemplate,
  Leaf,
  Library,
  ListChecks,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  Moon,
  Music,
  Package,
  Phone,
  Play,
  Quote,
  Send,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Stethoscope,
  Star,
  Users,
  Waves,
  type LucideIcon,
} from 'lucide-react';

export const iconMap: Record<string, LucideIcon> = {
  arrow: ArrowRight,
  book: BookOpen,
  brain: Brain,
  briefcase: Briefcase,
  calendar: CalendarDays,
  check: Check,
  clipboard: ClipboardCheck,
  clock: Clock,
  compass: Compass,
  download: Download,
  file: FileText,
  graduation: GraduationCap,
  heart: HeartPulse,
  home: Home,
  layout: LayoutTemplate,
  leaf: Leaf,
  library: Library,
  list: ListChecks,
  lock: Lock,
  mail: Mail,
  map: MapPin,
  message: MessageCircle,
  moon: Moon,
  music: Music,
  package: Package,
  phone: Phone,
  play: Play,
  quote: Quote,
  send: Send,
  shield: ShieldCheck,
  cart: ShoppingCart,
  sparkles: Sparkles,
  stethoscope: Stethoscope,
  star: Star,
  users: Users,
  waves: Waves,
};

export default function Icon({
  name,
  className = 'h-5 w-5',
}: {
  name: string;
  className?: string;
}) {
  const Cmp = iconMap[name] ?? Sparkles;
  return <Cmp className={className} aria-hidden="true" />;
}
